# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
- "app/Filtr/Utils/"
- "public/"
- "resources/"